### ISSUE TITLE
Project not running

### ISSUE THREAD

**Issue by Lechevallier** [tomaszs/react-library-vite#1]
Hi @tomaszs, thanks for the blog post and the repo, it's exactly what I'm trying to reproduce for my project since 2 days now.

However I have a problem at running your project.

I did install the dependencies in both folders `application` & `library`.

Then, running `pnpm dev` throw me this error:

```
VITE v4.4.5  ready in 1175 ms

  ➜  Local:   http://localhost:5173/
  ➜  Network: use --host to expose
  ➜  press h to show help
Error:   Failed to scan for dependencies from entries:
  /Users/maximelechevallier/Documents/MyProjects/react-library-vite/react-library-vite/application/index.html

  ✘ [ERROR] Failed to resolve entry for package "library". The package may have incorrect main/module/exports specified in its package.json. [plugin vite:dep-scan]

    node_modules/.pnpm/esbuild@0.18.20/node_modules/esbuild/lib/main.js:1373:21:
      1373 │         let result = await callback({
           ╵                      ^

    at packageEntryFailure (file:///Users/maximelechevallier/Documents/MyProjects/react-library-vite/react-library-vite/application/node_modules/.pnpm/vite@4.4.5/node_modules/vite/dist/node/chunks/dep-46921e22.js:28705:11)
    at resolvePackageEntry (file:///Users/maximelechevallier/Documents/MyProjects/react-library-vite/react-library-vite/application/node_modules/.pnpm/vite@4.4.5/node_modules/vite/dist/node/chunks/dep-46921e22.js:28702:5)
    at tryNodeResolve (file:///Users/maximelechevallier/Documents/MyProjects/react-library-vite/react-library-vite/application/node_modules/.pnpm/vite@4.4.5/node_modules/vite/dist/node/chunks/dep-46921e22.js:28436:20)
    at Context.resolveId (file:///Users/maximelechevallier/Documents/MyProjects/react-library-vite/react-library-vite/application/node_modules/.pnpm/vite@4.4.5/node_modules/vite/dist/node/chunks/dep-46921e22.js:28197:28)
    at Object.resolveId (file:///Users/maximelechevallier/Documents/MyProjects/react-library-vite/react-library-vite/application/node_modules/.pnpm/vite@4.4.5/node_modules/vite/dist/node/chunks/dep-46921e22.js:44145:64)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async resolve (file:///Users/maximelechevallier/Documents/MyProjects/react-library-vite/react-library-vite/application/node_modules/.pnpm/vite@4.4.5/node_modules/vite/dist/node/chunks/dep-46921e22.js:44458:26)
    at async file:///Users/maximelechevallier/Documents/MyProjects/react-library-vite/react-library-vite/application/node_modules/.pnpm/vite@4.4.5/node_modules/vite/dist/node/chunks/dep-46921e22.js:44635:34
    at async requestCallbacks.on-resolve (/Users/maximelechevallier/Documents/MyProjects/react-library-vite/react-library-vite/application/node_modules/.pnpm/esbuild@0.18.20/node_modules/esbuild/lib/main.js:1373:22)
    at async handleRequest (/Users/maximelechevallier/Documents/MyProjects/react-library-vite/react-library-vite/application/node_modules/.pnpm/esbuild@0.18.20/node_modules/esbuild/lib/main.js:729:13)

  This error came from the "onResolve" callback registered here:

    node_modules/.pnpm/esbuild@0.18.20/node_modules/esbuild/lib/main.js:1292:20:
      1292 │       let promise = setup({
           ╵                     ^

    at setup (file:///Users/maximelechevallier/Documents/MyProjects/react-library-vite/react-library-vite/application/node_modules/.pnpm/vite@4.4.5/node_modules/vite/dist/node/chunks/dep-46921e22.js:44625:19)
    at handlePlugins (/Users/maximelechevallier/Documents/MyProjects/react-library-vite/react-library-vite/application/node_modules/.pnpm/esbuild@0.18.20/node_modules/esbuild/lib/main.js:1292:21)
    at buildOrContextImpl (/Users/maximelechevallier/Documents/MyProjects/react-library-vite/react-library-vite/application/node_modules/.pnpm/esbuild@0.18.20/node_modules/esbuild/lib/main.js:978:5)
    at Object.buildOrContext (/Users/maximelechevallier/Documents/MyProjects/react-library-vite/react-library-vite/application/node_modules/.pnpm/esbuild@0.18.20/node_modules/esbuild/lib/main.js:786:5)
    at /Users/maximelechevallier/Documents/MyProjects/react-library-vite/react-library-vite/application/node_modules/.pnpm/esbuild@0.18.20/node_modules/esbuild/lib/main.js:2186:68
    at new Promise (<anonymous>)
    at Object.context (/Users/maximelechevallier/Documents/MyProjects/react-library-vite/react-library-vite/application/node_modules/.pnpm/esbuild@0.18.20/node_modules/esbuild/lib/main.js:2186:27)
    at Object.context (/Users/maximelechevallier/Documents/MyProjects/react-library-vite/react-library-vite/application/node_modules/.pnpm/esbuild@0.18.20/node_modules/esbuild/lib/main.js:2026:58)
    at prepareEsbuildScanner (file:///Users/maximelechevallier/Documents/MyProjects/react-library-vite/react-library-vite/application/node_modules/.pnpm/vite@4.4.5/node_modules/vite/dist/node/chunks/dep-46921e22.js:44400:26)

  The plugin "vite:dep-scan" was triggered by this import

    src/App.jsx:1:20:
      1 │ import { Foo } from 'library';
        ╵                     ~~~~~~~~~


    at failureErrorWithLog (/Users/maximelechevallier/Documents/MyProjects/react-library-vite/react-library-vite/application/node_modules/.pnpm/esbuild@0.18.20/node_modules/esbuild/lib/main.js:1649:15)
    at /Users/maximelechevallier/Documents/MyProjects/react-library-vite/react-library-vite/application/node_modules/.pnpm/esbuild@0.18.20/node_modules/esbuild/lib/main.js:1058:25
    at runOnEndCallbacks (/Users/maximelechevallier/Documents/MyProjects/react-library-vite/react-library-vite/application/node_modules/.pnpm/esbuild@0.18.20/node_modules/esbuild/lib/main.js:1484:45)
    at buildResponseToResult (/Users/maximelechevallier/Documents/MyProjects/react-library-vite/react-library-vite/application/node_modules/.pnpm/esbuild@0.18.20/node_modules/esbuild/lib/main.js:1056:7)
    at /Users/maximelechevallier/Documents/MyProjects/react-library-vite/react-library-vite/application/node_modules/.pnpm/esbuild@0.18.20/node_modules/esbuild/lib/main.js:1068:9
    at new Promise (<anonymous>)
    at requestCallbacks.on-end (/Users/maximelechevallier/Documents/MyProjects/react-library-vite/react-library-vite/application/node_modules/.pnpm/esbuild@0.18.20/node_modules/esbuild/lib/main.js:1067:54)
    at handleRequest (/Users/maximelechevallier/Documents/MyProjects/react-library-vite/react-library-vite/application/node_modules/.pnpm/esbuild@0.18.20/node_modules/esbuild/lib/main.js:729:19)
    at handleIncomingPacket (/Users/maximelechevallier/Documents/MyProjects/react-library-vite/react-library-vite/application/node_modules/.pnpm/esbuild@0.18.20/node_modules/esbuild/lib/main.js:755:7)
    at Socket.readFromStdout (/Users/maximelechevallier/Documents/MyProjects/react-library-vite/react-library-vite/application/node_modules/.pnpm/esbuild@0.18.20/node_modules/esbuild/lib/main.js:679:7)
    
    ```
    
    
By the way, I landed here thanks to [this issue](https://github.com/vitejs/vite/issues/14540) you posted on Vite repo. How did you fixed the original error?
    
Thanks a lot

**Comment by Lechevallier** [comment]
Had forgot to build the `library` first 🙈 

Still interested in [this issue](https://github.com/vitejs/vite/issues/14540) thoughts.

Thanks for the awesome work!
